In [ ]:
!pip install tensorflow

Requirement already satisfied: tensorflow in /usr/local/lib/python3.12/dist-packages (2.20.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from tensorflow) (26.1)
Requirement already satisfied: protobuf>=5.28.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (5.29.6)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.32.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from tensorflow) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.1.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.80.0)
Requirement already satisfied: tensorboard~=2.20.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.20.0)
Requirement already satisfied: keras>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.13.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.0.2)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.16.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.5.4)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from astunparse>=1.6.0->tensorflow) (0.47.0)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.10.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.10.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.10.0->tensorflow) (0.19.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2026.4.22)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (3.10.2)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (11.3.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (3.1.8)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from werkzeug>=1.0.1->tensorboard~=2.20.0->tensorflow) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.10.0->tensorflow) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.10.0->tensorflow) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.10.0->tensorflow) (0.1.2)

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("/content/Attrition - Attrition.csv")
df.head(3)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0

In [ ]:
df.isnull().sum()

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [ ]:
# df.info()

In [ ]:
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score

In [ ]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [ ]:
x = df.drop(columns=['Attrition'], axis=1)
y = df['Attrition']

In [ ]:
categorical_features = ['BusinessTravel',
      'Department',
      'EducationField',
      'Gender',
      'JobRole',
      'MaritalStatus',
      'Over18',
      'OverTime' ]

In [ ]:
x_encoded =pd.get_dummies(x, columns=categorical_features, drop_first = True)

In [ ]:
x_encoded = x_encoded.astype(int)

In [ ]:
x_encoded

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Married,MaritalStatus_Single,OverTime_Yes
0,41,1102,1,2,1,1,2,94,3,2,...,0,0,0,0,0,1,0,0,1,1
1,49,279,8,1,1,2,3,61,2,2,...,0,0,0,0,1,0,0,1,0,0
2,37,1373,2,2,1,4,4,92,2,1,...,1,0,0,0,0,0,0,0,1,1
3,33,1392,3,4,1,5,4,56,3,1,...,0,0,0,0,1,0,0,1,0,1
4,27,591,2,1,1,7,1,40,3,1,...,1,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,884,23,2,1,2061,3,41,4,2,...,1,0,0,0,0,0,0,1,0,0
1466,39,613,6,1,1,2062,4,42,2,3,...,0,0,0,0,0,0,0,1,0,0
1467,27,155,4,3,1,2064,2,87,4,2,...,0,0,1,0,0,0,0,1,0,1
1468,49,1023,2,3,1,2065,4,63,2,2,...,0,0,0,0,0,1,0,1,0,0
1469,34,628,8,3,1,2068,2,82,4,2,...,1,0,0,0,0,0,0,1,0,0

In [ ]:
# Encode target data
lb = LabelEncoder()

In [ ]:
y_encoded = lb.fit_transform(y)
y_encoded

array([1, 0, 1, ..., 0, 0, 0])

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x_encoded,
                                                    y_encoded,
                                                    test_size=0.2,
                                                    random_state=42)

In [ ]:
x_train.head()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Married,MaritalStatus_Single,OverTime_Yes
1097,24,350,21,2,1,1551,3,57,2,1,...,1,0,0,0,0,0,0,0,0,0
727,18,287,5,2,1,1012,2,73,3,1,...,0,0,0,0,1,0,0,0,1,0
254,29,1247,20,2,1,349,4,45,3,2,...,0,0,0,0,0,1,0,0,0,0
1175,39,492,12,3,1,1654,4,66,3,2,...,0,0,1,0,0,0,0,1,0,0
1341,31,311,20,3,1,1881,2,89,3,2,...,1,0,0,0,0,0,0,0,0,0

In [ ]:
sc = StandardScaler()

In [ ]:
x_train_scaled = sc.fit_transform(x_train)
x_test_scaled = sc.transform(x_test)

In [ ]:
# Now we will create architesture of our model

In [ ]:
model = tf. keras. models. Sequential ([
                tf.keras. layers. Dense(units = 128 , activation = 'relu' ,
                                      input_dim = x_train_scaled. shape[1]),  #input Layer
                tf.keras.layers.Dropout(0.3),
                tf.keras.layers.Dense(units = 64 , activation = 'relu'),      #hidden layer
                tf.keras.layers.Dropout(0.3),
                tf.keras. layers. Dense(units = 1 , activation = 'sigmoid')   #output Layer
])

In [ ]:
# Compile the Model

In [ ]:
loss_fn = tf.keras.losses.BinaryCrossentropy()
metrics = ['accuracy']

In [ ]:
learning_rate = 0.001
momentum = 0.9
optimizer = tf.keras.optimizers. SGD(learning_rate = learning_rate,
momentum = momentum , nesterov = True)

In [ ]:
model.compile(optimizer= optimizer, loss = loss_fn, metrics= metrics)

In [ ]:
# Train the Model

In [ ]:
model.fit(x_train_scaled,
          y_train,
          epochs = 50,
          batch_size = 8,
          validation_split = 0.1
)

Epoch 1/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.8195 - loss: 0.4900 - val_accuracy: 0.7966 - val_loss: 0.4985
Epoch 2/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.8346 - loss: 0.4536 - val_accuracy: 0.7966 - val_loss: 0.4672
Epoch 3/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8440 - loss: 0.4046 - val_accuracy: 0.8051 - val_loss: 0.4477
Epoch 4/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8384 - loss: 0.4038 - val_accuracy: 0.8136 - val_loss: 0.4367
Epoch 5/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8393 - loss: 0.4037 - val_accuracy: 0.8136 - val_loss: 0.4258
Epoch 6/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8431 - loss: 0.3805 - val_accuracy: 0.8051 - val_loss: 0.4181
Epoch 7/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8526 - loss: 0.3665 - val_accuracy: 0.8051 - val_loss: 0.4118
Epoch 8/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8601 - loss: 0.3398 - val_accuracy: 0.8305 - val_loss: 0.4060
Epoch 9/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8648 - loss: 0.3383 - val_accuracy: 0.8475 - val_loss: 0.3993
Epoch 10/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8639 - loss: 0.3452 - val_accuracy: 0.8305 - val_loss: 0.4010
Epoch 11/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8658 - loss: 0.3182 - val_accuracy: 0.8390 - val_loss: 0.4012
Epoch 12/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8781 - loss: 0.3187 - val_accuracy: 0.8475 - val_loss: 0.3958
Epoch 13/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8648 - loss: 0.3309 - val_accuracy: 0.8559 - val_loss: 0.3946
Epoch 14/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8894 - loss: 0.3009 - val_accuracy: 0.8475 - val_loss: 0.4006
Epoch 15/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8762 - loss: 0.3110 - val_accuracy: 0.8644 - val_loss: 0.3977
Epoch 16/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8866 - loss: 0.2964 - val_accuracy: 0.8644 - val_loss: 0.3983
Epoch 17/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8856 - loss: 0.2955 - val_accuracy: 0.8559 - val_loss: 0.3960
Epoch 18/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8837 - loss: 0.2882 - val_accuracy: 0.8644 - val_loss: 0.3982
Epoch 19/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8875 - loss: 0.2806 - val_accuracy: 0.8390 - val_loss: 0.3983
Epoch 20/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8828 - loss: 0.2748 - val_accuracy: 0.8305 - val_loss: 0.3999
Epoch 21/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8989 - loss: 0.2670 - val_accuracy: 0.8305 - val_loss: 0.3991
Epoch 22/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8866 - loss: 0.2821 - val_accuracy: 0.8305 - val_loss: 0.3987
Epoch 23/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8922 - loss: 0.2682 - val_accuracy: 0.8390 - val_loss: 0.4049
Epoch 24/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8809 - loss: 0.2785 - val_accuracy: 0.8390 - val_loss: 0.4031
Epoch 25/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9036 - loss: 0.2576 - val_accuracy: 0.8475 - val_loss: 0.4010
Epoch 26/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8979 - loss: 0.2758 - val_accuracy: 0.8559 - val_loss: 0.4031
Epoch 27/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8904 - loss: 0.2529 - val_accuracy: 0.8390 - val_loss: 0.4058
Epoch 28/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8960 - loss: 0.2697 - val_accuracy: 0.8390 - val_loss: 0.4048
Epoch 29/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8932 - loss: 0.2597 - val_accuracy: 0.8390 - val_loss: 0.4159
Epoch 30/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8970 - loss: 0.2535 - val_accuracy: 0.8305 - val_loss: 0.4146
Epoch 31/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8979 - loss: 0.2440 - val_accuracy: 0.8305 - val_loss: 0.4134
Epoch 32/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8998 - loss: 0.2445 - val_accuracy: 0.8305 - val_loss: 0.4190
Epoch 33/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8932 - loss: 0.2520 - val_accuracy: 0.8136 - val_loss: 0.4182
Epoch 34/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9064 - loss: 0.2436 - val_accuracy: 0.8390 - val_loss: 0.4222
Epoch 35/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9045 - loss: 0.2276 - val_accuracy: 0.8305 - val_loss: 0.4253
Epoch 36/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9045 - loss: 0.2396 - val_accuracy: 0.8390 - val_loss: 0.4327
Epoch 37/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9083 - loss: 0.2238 - val_accuracy: 0.8390 - val_loss: 0.4267
Epoch 38/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9206 - loss: 0.2127 - val_accuracy: 0.8220 - val_loss: 0.4247
Epoch 39/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9102 - loss: 0.2161 - val_accuracy: 0.8136 - val_loss: 0.4334
Epoch 40/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9008 - loss: 0.2260 - val_accuracy: 0.8220 - val_loss: 0.4420
Epoch 41/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9083 - loss: 0.2102 - val_accuracy: 0.8559 - val_loss: 0.4421
Epoch 42/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9112 - loss: 0.2214 - val_accuracy: 0.8559 - val_loss: 0.4451
Epoch 43/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9130 - loss: 0.2105 - val_accuracy: 0.8559 - val_loss: 0.4476
Epoch 44/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9140 - loss: 0.2090 - val_accuracy: 0.8559 - val_loss: 0.4396
Epoch 45/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9159 - loss: 0.2131 - val_accuracy: 0.8559 - val_loss: 0.4380
Epoch 46/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9244 - loss: 0.1949 - val_accuracy: 0.8644 - val_loss: 0.4395
Epoch 47/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9083 - loss: 0.2126 - val_accuracy: 0.8559 - val_loss: 0.4396
Epoch 48/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9168 - loss: 0.2076 - val_accuracy: 0.8390 - val_loss: 0.4427
Epoch 49/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9159 - loss: 0.2076 - val_accuracy: 0.8475 - val_loss: 0.4563
Epoch 50/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9149 - loss: 0.1961 - val_accuracy: 0.8644 - val_loss: 0.4622

In [ ]:
loss, accuracy = model.evaluate(x_test_scaled, y_test)

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8707 - loss: 0.3607

In [ ]:
print(f"Test Loss = {loss:4f}, Test Accuracy = {accuracy:4f}")

Test Loss = 0.360740, Test Accuracy = 0.870748

In [ ]:
# Workflow of Deep Learning

# # Data Ingestion ---- > Data Cleaning and Preprocessing --- >

# Model Sequnetial Architecture(
    # Inpput_Layer(Neurons, Activation fn, input_dimension),
    # hidden_Layer(Neurons, Activatin_fn),
    # output_Layer(Neurons, Activation_fn)
# )

# ModeL. compile(loss_fn , optimizer , metrics)
# Model.training
# Model Performance Evaluation

In [ ]:
cat_for_dummies = [col for col in cat if col in x.columns]